### PR TITLE
Use GetTypesImmediatelyDerivedFromInterfacesAsync

### LINKED ISSUE #21: Does not seem to be working in VS 2015 Update 2
I installed VS2015 Update 2 and before I installed, this extension was working, now it is not.

### PR DESCRIPTION
**Pull request by sharwell**
Use `GetTypesImmediatelyDerivedFromInterfacesAsync` when `FindDerivedInterfacesAsync` is missing.

Fixes #21

### CODE REVIEW

**Comment by bretthysuik** [comment]
@sharwell are you waiting for someone else to code review this or can it be merged in?

**Comment by xShivan** [comment]
Lack of this extension really slows me down (as well as my colleagues). Can you merge this pull request?

**Comment by sharwell** [comment]
@bretthysuik @xShivan I'm working on validating a few small changes for a new release today or tomorrow. :+1: 

In the meantime, would one of you be willing to test the [automated build result](https://ci.appveyor.com/project/sharwell/inheritancemargin/build/1.0.31/artifacts)? You should be able to install the VSIX by downloading it and double clicking it.

**Comment by bretthysuik** [comment]
That new build works for me (VS Professional 2015 v14.0.25123.00 Update 2)

**Comment by xShivan** [comment]
@sharwell that's awesome!

I confirm that automated build works fine for me with Visual Studio 2015 Enterprise with Update 2.

**Comment by xShivan** [comment]
That's great. Is there any estimate when the extension will be available at Visual Studio extension gallery?

**Comment by sharwell** [comment]
@bretthysuik @xShivan It's now available via the gallery. Thanks for the help!

**Comment by xShivan** [comment]
Awesome. Send me a PM if you need any help in the future.

**Pull request merged**
